contexts/v1.jsonld
index.html

This PR reworks the data model to address issue #2 and #3 by doing the following:
* The `type` field now includes a year... `StatusList2021`.
* The `statusPurpose` field has been added.
* The `statusPurpose` field contains a text string instead of a JSON-LD typed value.
* The `RevocationListX` and `SuspensionListX` types have been removed.
* Two text string status purposes "revocation" and "suspension" have been added.
* The JSON-LD Context and redirects have been fixed/updated.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-status-list-2021/pull/24.html" title="Last updated on Apr 4, 2022, 9:30 PM UTC (01a681d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-status-list-2021/24/abd4f1d...01a681d.html" title="Last updated on Apr 4, 2022, 9:30 PM UTC …

Rework the data model to support `statusPurpose` field.

---

index.html

Referencing this issue: https://github.com/w3c-ccg/vc-status-list-2021/issues/29
The example was a little misleading with the missing "id" field, adding it with this change.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 13, 2022, 7:51 PM UTC)_.
<details>
<summary>More</summary>
_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c-ccg/vc-status-list-2021%2330.)._
</details>

Per issue #29 - Adding "id" field to credentialStatus in example

---

index.html

The property is called `credentialStatus`, not `status`.
***
<a href="https://pr-preview.s3.amazonaws.com/nissimsan/vc-status-list-2021/pull/34.html" title="Last updated on Nov 22, 2022, 9:47 AM UTC (705d8cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-status-list-2021/34/c70e59f...nissimsan:705d8cb.html" title="Last updated on Nov 22, 2022, 9:47 AM UTC (705d8cb)">Diff</a>

fix: credentialStatus

---

index.html

This PR addresses issue #38 by specifying validity and caching behaviour for status list credentials.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-status-list-2021/pull/53.html" title="Last updated on Mar 6, 2023, 8:42 PM UTC (a399c83)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-status-list-2021/53/ca50a56...a399c83.html" title="Last updated on Mar 6, 2023, 8:42 PM UTC (a399c83)">Diff</a>

Add validity/caching period to status list credentials.

---

index.html

update to correct for my w3c id
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-status-list-2021/pull/59.html" title="Last updated on Apr 17, 2023, 1:33 PM UTC (493a368)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-status-list-2021/59/64afad4...493a368.html" title="Last updated on Apr 17, 2023, 1:33 PM UTC (493a368)">Diff</a>

Correct w3c id for mprorock

---

index.html

This PR addresses issue #39 by modifying the language in the specification to make it clear that if `statusListCredential` can't be dereferenced, that it should result in a validation error.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-status-list-2021/pull/46.html" title="Last updated on Feb 4, 2023, 10:03 PM UTC (854d60c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-status-list-2021/46/ca50a56...854d60c.html" title="Last updated on Feb 4, 2023, 10:03 PM UTC (854d60c)">Diff</a>

Ensure that statusListCredential can be dereferenced.

---

index.html

The respec plugin used in the core data model, does not work with v2 examples:
https://github.com/w3c/vc-data-model/blob/main/index.html#L13
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-status-list-2021/pull/67.html" title="Last updated on Jun 13, 2023, 5:28 PM UTC (b24a6fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-status-list-2021/67/aab9852...b24a6fd.html" title="Last updated on Jun 13, 2023, 5:28 PM UTC (b24a6fd)">Diff</a>

Add digital bazaar credential examples

---

index.html

initial additions for better caching guidance and backwards compatible support for multiple status value support in a single status list
Edit to note that TTL introduces a breaking change behavior, but the multiple status handling is backwards compatible with boolean status lists
***
<a href="https://pr-preview.s3.amazonaws.com/mesur-io/vc-status-list-2021/pull/65.html" title="Last updated on Jun 22, 2023, 5:09 PM UTC (887f87e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-status-list-2021/65/aab9852...mesur-io:887f87e.html" title="Last updated on Jun 22, 2023, 5:09 PM UTC (887f87e)">Diff</a>

Support for multiple status codes

---

index.html

This adds to the example both suspension and revocation lists, as discussed on https://github.com/w3c/vc-status-list-2021/issues/33 (and credit goes to @dlongley and @BenjaminMoe).
***
<a href="https://pr-preview.s3.amazonaws.com/nissimsan/vc-status-list-2021/pull/83.html" title="Last updated on Aug 31, 2023, 3:14 PM UTC (26a1291)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-status-list-2021/83/06e5483...nissimsan:26a1291.html" title="Last updated on Aug 31, 2023, 3:14 PM UTC (26a1291)">Diff</a>

Example both with revocation and suspension

---

index.html

Addresses:
- https://github.com/w3c/vc-bitstring-status-list/issues/78
- https://github.com/w3c/vc-bitstring-status-list/issues/41
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/92.html" title="Last updated on Dec 27, 2023, 9:02 PM UTC (57026fb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/92/875fece...57026fb.html" title="Last updated on Dec 27, 2023, 9:02 PM UTC (57026fb)">Diff</a>

Add section on media types

---

index.html

This PR renames the awkwardly named "status" "statusPurpose" field to "message" since the "statusPurpose" is about conveying arbitrary messages to verifiers. This PR will close out issue #42 if merged.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/100.html" title="Last updated on Dec 29, 2023, 11:52 PM UTC (94fb1cc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/100/843b1d6...94fb1cc.html" title="Last updated on Dec 29, 2023, 11:52 PM UTC (94fb1cc)">Diff</a>

Rename "status" to "message" for `statusPurpose` feature.

---

index.html

This PR attempts to address issue #7 by stating that the issuer of the original VC and the issuer of the status list VC might not be the same entity.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/103.html" title="Last updated on Jan 13, 2024, 3:58 PM UTC (612b477)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/103/843b1d6...612b477.html" title="Last updated on Jan 13, 2024, 3:58 PM UTC (612b477)">Diff</a>

Add note specifying that issuer might be different for status lists.

---

index.html

This PR is an attempt to address issue #9 by updating the validation algorithm to throw a RANGE_ERROR for indexes that are outside the length of a bitstring.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/104.html" title="Last updated on Jan 2, 2024, 7:46 PM UTC (9177a99)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/104/843b1d6...9177a99.html" title="Last updated on Jan 2, 2024, 7:46 PM UTC (9177a99)">Diff</a>

Throw RANGE_ERROR for indexes outside the length of a bitstring.

---

index.html

This is an attempt at addressing PR #35 by clarifying what the status information is about.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/106.html" title="Last updated on Dec 30, 2023, 12:04 AM UTC (364ec66)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/106/0ffc99b...364ec66.html" title="Last updated on Dec 30, 2023, 12:04 AM UTC (364ec66)">Diff</a>

Clarify what credential status information is about.

---

common.js
index.html

This PR is being raised to address issue #44 by stating that HTTPS should be used to publish status lists and protocols like OHTTP should be used to retrieve status lists.
These normative statements are untestable, so we might want to downgrade this language to advisement in the privacy considerations sections.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/107.html" title="Last updated on Dec 30, 2023, 12:05 AM UTC (3293cce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/107/0ffc99b...3293cce.html" title="Last updated on Dec 30, 2023, 12:05 AM UTC (3293cce)">Diff</a>

Add protocol statements related to pub/sub of status lists.

---

index.html

This PR attempts to address issue #51 by updating the normative dependency to the VCDM to v2.0. 
Note that the spec could also publish a context that enables usage of BitstringStatusList w/ v1.1 VCs if WG members desire that sort of functionality. WG members will have to step forward if they want this sort of backwards compatibility.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/108.html" title="Last updated on Jan 13, 2024, 4:28 PM UTC (12fd8ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/108/d7d4a47...12fd8ff.html" title="Last updated on Jan 13, 2024, 4:28 PM UTC (12fd8ff)">Diff</a>

Update VCDM dependency to VCDM v2.0.

---

contexts/2021/v1.jsonld
contexts/v1.jsonld
index.html
vocab/vocabulary.yml

This PR is an attempt at addressing issue #70, which updates the context to align with the latest specification. 
It preserves the old 2021 status list since that's where the w3id.org redirect goes currently, and we believe some organizations have deployed 2021 status list into potentially production environments. We need to preserve that file for now in order to not break implementations that aren't (mistakenly) caching their JSON-LD Contexts until we can move it back to the CCG or host it elsewhere (or decide to continue hosting it here).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/109.html" title="Last updated on Jan 13, 2024, 4:38 PM UTC (33d25b7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/109/887193d. …

Update BitstringStatusList context to align with latest spec.

---

index.html

This PR is an attempt to address issue #58 by clarifying that the base-encoding mechanism for `encodedList` is base64url.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/110.html" title="Last updated on Dec 30, 2023, 12:09 AM UTC (a12e3e9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/110/882b52f...a12e3e9.html" title="Last updated on Dec 30, 2023, 12:09 AM UTC (a12e3e9)">Diff</a>

Clarify base64 encoding as base64url encoding.

---

index.html

This PR is an attempt to address issue #94 by adding an optional normative mechanism to retrieve historical status list information.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/112.html" title="Last updated on Jan 13, 2024, 5:59 PM UTC (dfa5e31)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/112/b6883e5...dfa5e31.html" title="Last updated on Jan 13, 2024, 5:59 PM UTC (dfa5e31)">Diff</a>

Add mechanism to retrieve historical status list information.

---

index.html

This PR is an attempt to address issue #87 by raising an error when status list size does not meet minimum threshold.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/115.html" title="Last updated on Jan 13, 2024, 7:42 PM UTC (601246f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/115/26aaaf5...601246f.html" title="Last updated on Jan 13, 2024, 7:42 PM UTC (601246f)">Diff</a>

Raise error when status list size does not meet minimum threshold.

---

index.html

This PR is an attempt to address issue #86 by adding a privacy considerations section about Multistatus Correlation.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/117.html" title="Last updated on Jan 2, 2024, 8:40 PM UTC (c5bd70a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/117/a0a5eb3...c5bd70a.html" title="Last updated on Jan 2, 2024, 8:40 PM UTC (c5bd70a)">Diff</a>

Add privacy consideration section about Multistatus Correlation.

---

index.html

This PR is an attempt to address issue #52 by adding guidance on how to secure the status list.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/118.html" title="Last updated on Jan 13, 2024, 8:30 PM UTC (be298ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/118/dbe2e53...be298ab.html" title="Last updated on Jan 13, 2024, 8:30 PM UTC (be298ab)">Diff</a>

Add guidance on how to secure status lists.

---

index.html

This PR is an attempt to address issue #93 by adding an at risk issue marker to note that the bitstring format might change during the Candidate Recommendation phase if there is implementer interest to align more closely with the IETF Token Status List specification.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/119.html" title="Last updated on Jan 13, 2024, 8:59 PM UTC (078db10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/119/9a44436...078db10.html" title="Last updated on Jan 13, 2024, 8:59 PM UTC (078db10)">Diff</a>

Add "at risk" marker noting bitstring format might change in CR.

---

index.html

This is a simple editorial rename of "herd privacy" to "group privacy". Some in the group find the term "herd", when applied to humans, as mildly offensive. The counter argument is that we're all animals too. :P
The term "group privacy" is used as synonymous to "herd privacy" in much of the literature I found during a quick search to see if this would create confusion among readers that go searching for literature. "Group privacy" also wins the [Google trends search](https://trends.google.com/trends/explore?date=all&q=herd%20privacy,group%20privacy&hl=en) for the past 20-ish years.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/121.html" title="Last updated on Jan 13, 2024, 9:02 PM UTC (3d1e94b)">Preview</a> | <a …

Rename "herd privacy" to "group privacy".

---

index.html

This PR is an attempt at addressing [some comments](https://github.com/w3c/vc-bitstring-status-list/issues/73#issuecomment-1872490184) in issue #73 by adding examples for multiple status lists and multiple entries in a single status list.
Note: This PR contains a normative change to support the last example with multiple status types stored in a single list. It also has an at-risk marker for the feature as the more I wrote about the feature, the less of a benefit there seemed to be. The strongest benefit seems to be a privacy argument (if you mix in multiple statuses in a single list, and the bits for each status don't sit beside one another, it's hard to tell which type of status bit is being flipped to an outside observer -- which improves the privacy characteristics of the list).
*** …

Add examples for multiple status lists and multiple entries in a single status list

---

CONTRIBUTING.md
index.html

This PR is an attempt at addressing [some comments](https://github.com/w3c/vc-bitstring-status-list/issues/73#issuecomment-1872490184) in issue #73 by marking the multibit status entry feature as at risk. The PR makes it such that implementers don't have to implement the feature to have a conforming processor, but allows implementations that need the feature to implement it in an interoperable fashion.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/123.html" title="Last updated on Jan 2, 2024, 8:47 PM UTC (2d24d4a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/123/9988e57...2d24d4a.html" title="Last updated on Jan 2, 2024, 8:47 PM UTC (2d24d4a)">Diff</a>

Add at risk issue marker regarding multibit status entries.

---

index.html

This PR is an attempt to address issue #120 by adding an at risk issue marker regarding the conflict between the `ttl` value and the `validUntil` value. The PR also removes the ellipsis around `proof` since we did that in the main spec as well. As soon as we update `respec-vc`, we'll add examples encoded in DI and SD-JWT.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/128.html" title="Last updated on Jan 21, 2024, 11:07 PM UTC (05bccaf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/128/3c87c08...05bccaf.html" title="Last updated on Jan 21, 2024, 11:07 PM UTC (05bccaf)">Diff</a>

Add at risk issue marker for TTL.

---

index.html

This PR is an attempt to address issue #124 by explicitly noting that the `issuer` value for a `BitstringStatusListCredential` MAY be different from the `issuer` value of the associated VC.
/cc @jchartrand
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/129.html" title="Last updated on Jan 21, 2024, 11:09 PM UTC (32b32ca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/129/3c87c08...32b32ca.html" title="Last updated on Jan 21, 2024, 11:09 PM UTC (32b32ca)">Diff</a>

Explicitly allow `issuer` to be different between VC and BSLC.

---

contexts/v1.jsonld
index.html
vocab/vocabulary.yml

This PR is an attempt to address issue #125 by strictly typing the `encodedList` value to ensure that it can be automatically converted to a pure binary value.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/130.html" title="Last updated on Jan 21, 2024, 11:15 PM UTC (97b2010)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/130/fa75c28...97b2010.html" title="Last updated on Jan 21, 2024, 11:15 PM UTC (97b2010)">Diff</a>

Ensure better compression for `encodedList` by typing the value.

---

vocab/template.html
vocab/vocabulary.yml

yml2vocab has now the ability of adding information on designated @context files that contain individual terms to the output. This change is adapted to this vocabulary.
No changes on the vocabulary content itself.
As usual, the automatic preview is useless for this case, see https://w3c.github.io/yml2vocab/previews/sl/ for the new versions of the generated files.

Update vocabulary and template files

---

index.html

This PR is an attempt to address issue #140 by clarifying how internationalization support is provided for processing error messages.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/152.html" title="Last updated on Mar 30, 2024, 3:15 PM UTC (3c553d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/152/c28ea0a...3c553d0.html" title="Last updated on Mar 30, 2024, 3:15 PM UTC (3c553d0)">Diff</a>

Clarify internationalization mechanism for Processing Errors.

---

index.html

This PR is an attempt to address issue #144 and #145 by providing normative guidance to both issuers and verifiers on publishing, retrieval, and caching behaviour.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/153.html" title="Last updated on Mar 30, 2024, 3:23 PM UTC (8510cc4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/153/8287319...8510cc4.html" title="Last updated on Mar 30, 2024, 3:23 PM UTC (8510cc4)">Diff</a>

Add normative statements related to caching of status list VCs.

---

index.html

This PR is an attempt to address issue #149 by being more specific about the randomization requirements for the status list index.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/154.html" title="Last updated on Mar 30, 2024, 6:22 PM UTC (c0bb5e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/154/c28ea0a...c0bb5e1.html" title="Last updated on Mar 30, 2024, 6:22 PM UTC (c0bb5e1)">Diff</a>

Clarify normative text around randomness of list index.

---

index.html

This PR is an attempt to address issue #146 by documenting how status messages could be used to accidentally expose more information about a holder than they originally thought and how holder software could be used to warn the holder of changes in status message information.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/156.html" title="Last updated on Mar 30, 2024, 7:08 PM UTC (83805bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/156/c28ea0a...83805bb.html" title="Last updated on Mar 30, 2024, 7:08 PM UTC (83805bb)">Diff</a>

Add privacy considerations about status message updates/alterations.

---

index.html

This PR is an attempt to address issue #150 by providing guidance around decoy values.
/cc @zoracon
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/155.html" title="Last updated on Apr 6, 2024, 5:57 PM UTC (331d95f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/155/9ee8c7e...331d95f.html" title="Last updated on Apr 6, 2024, 5:57 PM UTC (331d95f)">Diff</a>

Add privacy considerations section about decoy values.

---

vocab/template.html
vocab/vocabulary.drawio
vocab/vocabulary.svg
vocab/vocabulary.yml

This PR implements the changes proposed in #158, adds a diagram (with its textual description) to the generated HTML+RDFa file to be in line in style with the other vocabularies.
As usual, the built-in preview would not help for the generated vocabulary files and the diagrams. The preview page to be used is here: https://w3c.github.io/yml2vocab/previews/sl/

Added changes to the vocabulary per #158

---

index.html

This PR is an attempt to address issue #142 and #147 by providing some guidance on when it's appropriate to use status lists that contain globally unique identifiers and when status lists should be selectively disclosable.
/cc @zoracon
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/160.html" title="Last updated on Apr 6, 2024, 6:11 PM UTC (ed3f86f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/160/065e536...ed3f86f.html" title="Last updated on Apr 6, 2024, 6:11 PM UTC (ed3f86f)">Diff</a>

Add Privacy Considerations section on "Unnecessary Correlation".

---

index.html

This PR is an attempt to address issue #48, #49, and #148 by documenting other approaches that were considered for status lists and detailing why status lists are expressed as VCs.
/cc @zoracon
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/162.html" title="Last updated on Apr 6, 2024, 6:24 PM UTC (2e0b74f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/162/065e536...2e0b74f.html" title="Last updated on Apr 6, 2024, 6:24 PM UTC (2e0b74f)">Diff</a>

Add comparison matrix and stapling language.

---

index.html

Status field should be machine readable, message should be human readable, I changed the example to make the message more clearly human readable.
***
<a href="https://pr-preview.s3.amazonaws.com/Mavennet/vc-bitstring-status-list/pull/138.html" title="Last updated on Apr 6, 2024, 7:10 PM UTC (86fd178)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/138/6c5f490...Mavennet:86fd178.html" title="Last updated on Apr 6, 2024, 7:10 PM UTC (86fd178)">Diff</a>

added human readable/machine readable, changed example to be more clear.

---

index.html

This PR attempts to address issue #143 by adding guidance on how holder software can detect malicious issuers that inject tracking identifiers into their credentials.
/cc @zoracon
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/161.html" title="Last updated on Apr 16, 2024, 7:50 PM UTC (7fb0dd2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/161/065e536...7fb0dd2.html" title="Last updated on Apr 16, 2024, 7:50 PM UTC (7fb0dd2)">Diff</a>

Add suggestion on how malicious issuers can be detected.

---

index.html

This PR is an attempt to address issue #151 by requiring that status messages are committed to by issuers at issuance time. The PR does this by:
* Moving the `statusSize`, `statusMessage`, and `statusReference` fields to the `BitstringStatusListEntry` object.
* Explaining why the commitment is done at issuance time on the original VC itself.
NOTE TO REVIEWERS: Most of the changes in this PR are just moving text around in the spec. The only normative change is the first bullet item above. Everything else should be editorial. It looks like way more changed than it did.
I believe, if this PR is accepted, that it should address @jandrieu and PINGs concerns regarding the issuer changing the types of status messages that are possible without the holder or subjects knowledge.
***
<a …

Ensure that status messages are committed to at issuance time.

---

CR/2024-05-09/index.html
index.html

Changing the core index.html and the CR dump to answer PlH's request in https://github.com/w3c/transitions/issues/603#issuecomment-2092978449.
If this PR is correct spec-wise (@msporny ?) and is what PlH is waiting for (@plehegar ?) then, after merging, we may still get an approval for a publication next Thursday _and_ I can take care of it before I disappear for my break...
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/170.html" title="Last updated on May 3, 2024, 1:40 PM UTC (e58098d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/170/d3b6981...e58098d.html" title="Last updated on May 3, 2024, 1:40 PM UTC (e58098d)">Diff</a>

Added a reference to optional features in SOTD

---

index.html

This PR is an attempt to note that issue #150 will be addressed in CR, with more direct involvement by PING (and other concerned parties), by performing a more detailed analysis on decoy values.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/171.html" title="Last updated on May 14, 2024, 1:02 PM UTC (eee3c71)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/171/b571224...eee3c71.html" title="Last updated on May 14, 2024, 1:02 PM UTC (eee3c71)">Diff</a>

Add issue marker noting guidance about decoy values will be resolved in CR.

---

index.html

This adds specific instructions on the generate/expand bitstring algorithms to use multibase base64url instead of just base64url to be consistent with the data model section.
addresses #178
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/179.html" title="Last updated on Nov 18, 2024, 2:01 AM UTC (d7146a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/179/47e1900...d7146a4.html" title="Last updated on Nov 18, 2024, 2:01 AM UTC (d7146a4)">Diff</a>

Specify to use multibase representation of the base64url algorithm.

---

index.html

Removes integer codes from problem details along with normative statements.
Addresses #180
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/181.html" title="Last updated on Oct 13, 2024, 8:47 PM UTC (2051e56)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/181/47e1900...2051e56.html" title="Last updated on Oct 13, 2024, 8:47 PM UTC (2051e56)">Diff</a>

Remove integer codes from problem details

---

index.html

This PR is an attempt to address issue #183 by adding a `refresh` status purpose.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/185.html" title="Last updated on Nov 30, 2024, 6:09 PM UTC (4908579)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/185/8af361e...4908579.html" title="Last updated on Nov 30, 2024, 6:09 PM UTC (4908579)">Diff</a>

Add `refresh` status purpose.

---

index.html

This PR is an attempt to address issue #174 by clarifying that TTL is optional and doesn't override the credential's validity period.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Nov 24, 2024, 11:22 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL]([object Object])
```
Timed out after waiting 30000ms
```
_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an …

Clarify that TTL is optional and doesn't override validity.

---

index.html

This PR is an attempt to address issue #188 by adding references to the vocabulary and context files.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/189.html" title="Last updated on Nov 30, 2024, 7:30 PM UTC (a50893f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/189/7727b69...a50893f.html" title="Last updated on Nov 30, 2024, 7:30 PM UTC (a50893f)">Diff</a>

Add context and vocabulary section.

---

index.html

This PR is an attempt to address issue #48 by providing guidance on how to choose validity periods for status lists.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Dec 2, 2024, 7:00 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL]([object Object])
```
Protocol error (Runtime.callFunctionOn): Promise was collected
```
_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an …

Provide guidance on choosing validity periods for status lists.

---

index.html

This PR is an attempt to address issue #150 by providing guidance on the use of decoy values.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/pull/191.html" title="Last updated on Dec 8, 2024, 8:21 PM UTC (d1f6c63)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/191/c046869...d1f6c63.html" title="Last updated on Dec 8, 2024, 8:21 PM UTC (d1f6c63)">Diff</a>

Provide guidance on using decoy values.

---

vocab/vocabulary.yml

This means that the references to the relevant context files will appear for each term. (See the [di vocabulary description](https://w3c.github.io/vc-data-integrity/vocab/security/vocabulary.html#context-files) as a reference to what this means).

Added the context references to the vocabulary.yml file

---

index.html

to look up the entry in the status list.
Addresses #184
***
<a href="https://pr-preview.s3.amazonaws.com/LegReq/vc-bitstring-status-list/pull/196.html" title="Last updated on Jan 9, 2025, 4:41 PM UTC (30edd72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-bitstring-status-list/196/2064063...LegReq:30edd72.html" title="Last updated on Jan 9, 2025, 4:41 PM UTC (30edd72)">Diff</a>

added note clarifying that credentialSubject.id is not used 
